import json

# error_codes.py
# Centralized definition of all error codes across the tax rule engine

class ErrorCodes:
    # 80C
    LIMIT_EXCEEDED_80C = "80C_LIMIT_EXCEEDED"
    NOT_ALLOWED_IN_NEW_REGIME_80C = "80C_NOT_ALLOWED_IN_NEW_REGIME"
    
    # 80D
    LIMIT_EXCEEDED_80D = "80D_LIMIT_EXCEEDED"
    NOT_ALLOWED_IN_NEW_REGIME_80D = "80D_NOT_ALLOWED_IN_NEW_REGIME"
    
    # NPS (80CCD)
    LIMIT_EXCEEDED_NPS_80CCD1B = "NPS_80CCD1B_LIMIT_EXCEEDED"
    LIMIT_EXCEEDED_NPS_80CCD2 = "NPS_80CCD2_LIMIT_EXCEEDED"
    NOT_ALLOWED_IN_NEW_REGIME_80CCD1B = "80CCD1B_NOT_ALLOWED_IN_NEW_REGIME"

    # HRA
    NOT_ALLOWED_IN_NEW_REGIME_HRA = "HRA_NOT_ALLOWED_IN_NEW_REGIME"
    
    # Standard Deduction
    INVALID_STANDARD_DEDUCTION = "INVALID_STANDARD_DEDUCTION_LIMIT"
    
    # Z3 Regime Clash
    INVALID_REGIME_SELECTION = "INVALID_REGIME_SELECTION"
    REGIME_CLASH = "CONSTRAINT_VIOLATION_DUE_TO_REGIME"
